<?php

namespace app\app\core\config;

use app\app\core\Router;

class Route extends Router
{
    public static function get($action, $callback): void
    {
        parent::get($action, $callback); // TODO: Change the autogenerated stub
    }

    public static function post($action, $callback): void
    {
        parent::post($action, $callback); // TODO: Change the autogenerated stub
    }

    public static function run($action): void
    {
        parent::run($action); // TODO: Change the autogenerated stub
    }
}